/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedInvoiceLine service. Represents a row in the &quot;CustomInvoice_PersistedInvoiceLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.model.impl.PersistedInvoiceLineModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.model.impl.PersistedInvoiceLineImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedInvoiceLine
 * @generated
 */
@ProviderType
public interface PersistedInvoiceLineModel
	extends BaseModel<PersistedInvoiceLine>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted invoice line model instance should use the {@link PersistedInvoiceLine} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted invoice line.
	 *
	 * @return the primary key of this persisted invoice line
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted invoice line.
	 *
	 * @param primaryKey the primary key of this persisted invoice line
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the persisted invoice line ID of this persisted invoice line.
	 *
	 * @return the persisted invoice line ID of this persisted invoice line
	 */
	public long getPersistedInvoiceLineId();

	/**
	 * Sets the persisted invoice line ID of this persisted invoice line.
	 *
	 * @param persistedInvoiceLineId the persisted invoice line ID of this persisted invoice line
	 */
	public void setPersistedInvoiceLineId(long persistedInvoiceLineId);

	/**
	 * Returns the group ID of this persisted invoice line.
	 *
	 * @return the group ID of this persisted invoice line
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this persisted invoice line.
	 *
	 * @param groupId the group ID of this persisted invoice line
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this persisted invoice line.
	 *
	 * @return the company ID of this persisted invoice line
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted invoice line.
	 *
	 * @param companyId the company ID of this persisted invoice line
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted invoice line.
	 *
	 * @return the user ID of this persisted invoice line
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted invoice line.
	 *
	 * @param userId the user ID of this persisted invoice line
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted invoice line.
	 *
	 * @return the user uuid of this persisted invoice line
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted invoice line.
	 *
	 * @param userUuid the user uuid of this persisted invoice line
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted invoice line.
	 *
	 * @return the user name of this persisted invoice line
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted invoice line.
	 *
	 * @param userName the user name of this persisted invoice line
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted invoice line.
	 *
	 * @return the create date of this persisted invoice line
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted invoice line.
	 *
	 * @param createDate the create date of this persisted invoice line
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted invoice line.
	 *
	 * @return the modified date of this persisted invoice line
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted invoice line.
	 *
	 * @param modifiedDate the modified date of this persisted invoice line
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the persisted invoice ID of this persisted invoice line.
	 *
	 * @return the persisted invoice ID of this persisted invoice line
	 */
	public long getPersistedInvoiceId();

	/**
	 * Sets the persisted invoice ID of this persisted invoice line.
	 *
	 * @param persistedInvoiceId the persisted invoice ID of this persisted invoice line
	 */
	public void setPersistedInvoiceId(long persistedInvoiceId);

	/**
	 * Returns the price of this persisted invoice line.
	 *
	 * @return the price of this persisted invoice line
	 */
	public double getPrice();

	/**
	 * Sets the price of this persisted invoice line.
	 *
	 * @param price the price of this persisted invoice line
	 */
	public void setPrice(double price);

	/**
	 * Returns the quantity of this persisted invoice line.
	 *
	 * @return the quantity of this persisted invoice line
	 */
	public Integer getQuantity();

	/**
	 * Sets the quantity of this persisted invoice line.
	 *
	 * @param quantity the quantity of this persisted invoice line
	 */
	public void setQuantity(Integer quantity);

	/**
	 * Returns the discount percent of this persisted invoice line.
	 *
	 * @return the discount percent of this persisted invoice line
	 */
	public double getDiscountPercent();

	/**
	 * Sets the discount percent of this persisted invoice line.
	 *
	 * @param discountPercent the discount percent of this persisted invoice line
	 */
	public void setDiscountPercent(double discountPercent);

	/**
	 * Returns the item code of this persisted invoice line.
	 *
	 * @return the item code of this persisted invoice line
	 */
	@AutoEscape
	public String getItemCode();

	/**
	 * Sets the item code of this persisted invoice line.
	 *
	 * @param itemCode the item code of this persisted invoice line
	 */
	public void setItemCode(String itemCode);

	/**
	 * Returns the line num of this persisted invoice line.
	 *
	 * @return the line num of this persisted invoice line
	 */
	public Integer getLineNum();

	/**
	 * Sets the line num of this persisted invoice line.
	 *
	 * @param lineNum the line num of this persisted invoice line
	 */
	public void setLineNum(Integer lineNum);

	/**
	 * Returns the line total of this persisted invoice line.
	 *
	 * @return the line total of this persisted invoice line
	 */
	public double getLineTotal();

	/**
	 * Sets the line total of this persisted invoice line.
	 *
	 * @param lineTotal the line total of this persisted invoice line
	 */
	public void setLineTotal(double lineTotal);

	/**
	 * Returns the sales order of this persisted invoice line.
	 *
	 * @return the sales order of this persisted invoice line
	 */
	public long getSalesOrder();

	/**
	 * Sets the sales order of this persisted invoice line.
	 *
	 * @param salesOrder the sales order of this persisted invoice line
	 */
	public void setSalesOrder(long salesOrder);

	/**
	 * Returns the sales orderline num of this persisted invoice line.
	 *
	 * @return the sales orderline num of this persisted invoice line
	 */
	public Integer getSalesOrderlineNum();

	/**
	 * Sets the sales orderline num of this persisted invoice line.
	 *
	 * @param salesOrderlineNum the sales orderline num of this persisted invoice line
	 */
	public void setSalesOrderlineNum(Integer salesOrderlineNum);

}