/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedInvoice service. Represents a row in the &quot;CustomInvoice_PersistedInvoice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.model.impl.PersistedInvoiceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.model.impl.PersistedInvoiceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedInvoice
 * @generated
 */
@ProviderType
public interface PersistedInvoiceModel
	extends BaseModel<PersistedInvoice>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted invoice model instance should use the {@link PersistedInvoice} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted invoice.
	 *
	 * @return the primary key of this persisted invoice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted invoice.
	 *
	 * @param primaryKey the primary key of this persisted invoice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the persisted invoice ID of this persisted invoice.
	 *
	 * @return the persisted invoice ID of this persisted invoice
	 */
	public long getPersistedInvoiceId();

	/**
	 * Sets the persisted invoice ID of this persisted invoice.
	 *
	 * @param persistedInvoiceId the persisted invoice ID of this persisted invoice
	 */
	public void setPersistedInvoiceId(long persistedInvoiceId);

	/**
	 * Returns the group ID of this persisted invoice.
	 *
	 * @return the group ID of this persisted invoice
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this persisted invoice.
	 *
	 * @param groupId the group ID of this persisted invoice
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this persisted invoice.
	 *
	 * @return the company ID of this persisted invoice
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted invoice.
	 *
	 * @param companyId the company ID of this persisted invoice
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted invoice.
	 *
	 * @return the user ID of this persisted invoice
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted invoice.
	 *
	 * @param userId the user ID of this persisted invoice
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted invoice.
	 *
	 * @return the user uuid of this persisted invoice
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted invoice.
	 *
	 * @param userUuid the user uuid of this persisted invoice
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted invoice.
	 *
	 * @return the user name of this persisted invoice
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted invoice.
	 *
	 * @param userName the user name of this persisted invoice
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted invoice.
	 *
	 * @return the create date of this persisted invoice
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted invoice.
	 *
	 * @param createDate the create date of this persisted invoice
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted invoice.
	 *
	 * @return the modified date of this persisted invoice
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted invoice.
	 *
	 * @param modifiedDate the modified date of this persisted invoice
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the gst of this persisted invoice.
	 *
	 * @return the gst of this persisted invoice
	 */
	public double getGst();

	/**
	 * Sets the gst of this persisted invoice.
	 *
	 * @param gst the gst of this persisted invoice
	 */
	public void setGst(double gst);

	/**
	 * Returns the card code of this persisted invoice.
	 *
	 * @return the card code of this persisted invoice
	 */
	@AutoEscape
	public String getCardCode();

	/**
	 * Sets the card code of this persisted invoice.
	 *
	 * @param cardCode the card code of this persisted invoice
	 */
	public void setCardCode(String cardCode);

	/**
	 * Returns the card name of this persisted invoice.
	 *
	 * @return the card name of this persisted invoice
	 */
	@AutoEscape
	public String getCardName();

	/**
	 * Sets the card name of this persisted invoice.
	 *
	 * @param cardName the card name of this persisted invoice
	 */
	public void setCardName(String cardName);

	/**
	 * Returns the carrier of this persisted invoice.
	 *
	 * @return the carrier of this persisted invoice
	 */
	@AutoEscape
	public String getCarrier();

	/**
	 * Sets the carrier of this persisted invoice.
	 *
	 * @param carrier the carrier of this persisted invoice
	 */
	public void setCarrier(String carrier);

	/**
	 * Returns the document date of this persisted invoice.
	 *
	 * @return the document date of this persisted invoice
	 */
	public Date getDocumentDate();

	/**
	 * Sets the document date of this persisted invoice.
	 *
	 * @param documentDate the document date of this persisted invoice
	 */
	public void setDocumentDate(Date documentDate);

	/**
	 * Returns the document number of this persisted invoice.
	 *
	 * @return the document number of this persisted invoice
	 */
	@AutoEscape
	public String getDocumentNumber();

	/**
	 * Sets the document number of this persisted invoice.
	 *
	 * @param documentNumber the document number of this persisted invoice
	 */
	public void setDocumentNumber(String documentNumber);

	/**
	 * Returns the document status of this persisted invoice.
	 *
	 * @return the document status of this persisted invoice
	 */
	@AutoEscape
	public String getDocumentStatus();

	/**
	 * Sets the document status of this persisted invoice.
	 *
	 * @param documentStatus the document status of this persisted invoice
	 */
	public void setDocumentStatus(String documentStatus);

	/**
	 * Returns the due date of this persisted invoice.
	 *
	 * @return the due date of this persisted invoice
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this persisted invoice.
	 *
	 * @param dueDate the due date of this persisted invoice
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the freight amount of this persisted invoice.
	 *
	 * @return the freight amount of this persisted invoice
	 */
	public double getFreightAmount();

	/**
	 * Sets the freight amount of this persisted invoice.
	 *
	 * @param freightAmount the freight amount of this persisted invoice
	 */
	public void setFreightAmount(double freightAmount);

	/**
	 * Returns the invoice total of this persisted invoice.
	 *
	 * @return the invoice total of this persisted invoice
	 */
	public double getInvoiceTotal();

	/**
	 * Sets the invoice total of this persisted invoice.
	 *
	 * @param invoiceTotal the invoice total of this persisted invoice
	 */
	public void setInvoiceTotal(double invoiceTotal);

	/**
	 * Returns the commerce account ID of this persisted invoice.
	 *
	 * @return the commerce account ID of this persisted invoice
	 */
	public long getCommerceAccountId();

	/**
	 * Sets the commerce account ID of this persisted invoice.
	 *
	 * @param commerceAccountId the commerce account ID of this persisted invoice
	 */
	public void setCommerceAccountId(long commerceAccountId);

}